from typing import Protocol, TYPE_CHECKING

if TYPE_CHECKING:
    from models import StudyMaterial


class MaterialRepositoryPort(Protocol):
    def deactivate_all(self, student_id: int, commit: bool = True) -> bool: ...
    def find_by_source(self, student_id: int, source_name: str): ...
    def save_material(self, material): ...
    def load(self, student_id: int): ...
    def get_stats(self, student_id: int, material_id: int) -> dict | None: ...
    def get_stats_by_id(self, material_id: int) -> dict | None: ...
    def get_concept_id_map(self, material_id: int) -> dict[str, int]: ...
    def get_concept_pairs(self, material_id: int) -> list[tuple[str, str]]: ...
    def get_concept_pairs_for_student(self, student_id: int) -> list[tuple[str, str]]: ...
    def set_stats(self, material_id: int, total_questions_answered: int, correct_answers_count: int, total_xp: int, high_score: int) -> bool: ...
    def clear(self, student_id: int) -> bool: ...
    def list_all(self, student_id: int) -> list["StudyMaterial"]: ...
    def activate(self, student_id: int, material_id: int) -> bool: ...
    def delete(self, student_id: int, material_id: int) -> bool: ...


class QuizRepositoryPort(Protocol):
    def save_quiz_result(self, student_id: int, score: int, total: int, quiz_type: str, analytics_data: list[dict], material_id: int | None = None) -> bool: ...
    def delete_results_for_material(self, material_id: int) -> int: ...


class StudentRepositoryPort(Protocol):
    def create_student(self, name: str, password: str): ...
    def authenticate_student(self, name: str, password: str): ...
    def get_student(self, student_id: int): ...
    def update_xp(self, student_id: int, amount: int): ...
    def update_avatar(self, student_id: int, avatar: str): ...
    def update_high_score(self, student_id: int, score: int): ...


class QuizAIServicePort(Protocol):
    client: object | None
    def generate_quiz(self, strategy, text: str, topics: list[str] | None = None, priority_topics: list[str] | None = None, material_concepts: list[str] | None = None) -> list[dict] | None: ...
    def evaluate_answer(self, text: str, question: str, user_answer: str, quiz_type: str = "open-ended") -> dict: ...


class TopicAIServicePort(Protocol):
    client: object | None
    def extract_topics(self, text: str) -> dict[str, list[str]]: ...


class AnalyticsRepositoryPort(Protocol):
    def fetch_question_analytics(self, student_id: int, material_id: int | None = None) -> list[dict]: ...


class OpenAIClientPort(Protocol):
    def chat_completions_create(self, **kwargs): ...
