from typing import Protocol, TYPE_CHECKING, Any

if TYPE_CHECKING:
    pass


class StudentGamificationRepositoryPort(Protocol):
    def update_xp(self, student_id: int, amount: int) -> Any: ...
    def update_avatar(self, student_id: int, avatar: str) -> Any: ...
    def update_high_score(self, student_id: int, score: int) -> Any: ...


class GamificationServicePort(Protocol):
    def add_xp(self, student_id: int, amount: int) -> Any: ...
    def update_avatar(self, student_id: int, avatar: str) -> Any: ...
    def update_high_score(self, student_id: int, score: int) -> Any: ...
