from typing import Protocol, TYPE_CHECKING, List, Dict, Any, Optional

if TYPE_CHECKING:
    pass


class AnalyticsServicePort(Protocol):
    def get_weak_points(self, student_id: int, material_id: int | None = None) -> Any: ...
    def get_adaptive_topics(self, student_id: int, material_id: int | None = None) -> Any: ...
    def get_recent_metrics(self, student_id: int, days: int = 30, tz_offset_minutes: int = 0) -> Any: ...


class AnalyticsRepositoryPort(Protocol):
    def fetch_question_analytics(self, student_id: int, material_id: int | None = None) -> List[Dict]: ...
    def fetch_quiz_sessions(self, student_id: int, start_utc, end_utc) -> List[Dict]: ...
