from typing import Protocol, TYPE_CHECKING, Dict, List, Optional, Tuple, Any

if TYPE_CHECKING:
    from models import StudyMaterial


class MaterialUpsertRepositoryPort(Protocol):
    def deactivate_all(self, student_id: int, commit: bool = True) -> bool: ...
    def find_by_source(self, student_id: int, source_name: str) -> Any: ...
    def save_material(self, material: Any) -> Any: ...


class MaterialLoaderPort(Protocol):
    def load(self, student_id: int) -> Any: ...


class MaterialReaderRepositoryPort(Protocol):
    def load(self, student_id: int) -> Any: ...
    def list_all(self, student_id: int) -> List["StudyMaterial"]: ...
    def activate(self, student_id: int, material_id: int) -> bool: ...
    def clear(self, student_id: int) -> bool: ...


class MaterialDeletionRepositoryPort(Protocol):
    def get_stats(self, student_id: int, material_id: int) -> Dict | None: ...
    def delete(self, student_id: int, material_id: int) -> bool: ...


class MaterialStatsRepositoryPort(Protocol):
    def get_stats_by_id(self, material_id: int) -> Dict | None: ...
    def set_stats(self, material_id: int, total_questions_answered: int, correct_answers_count: int, total_xp: int, high_score: int) -> bool: ...


class MaterialConceptIdRepositoryPort(Protocol):
    def get_concept_id_map(self, material_id: int) -> Dict[str, int]: ...


class MaterialConceptPairsRepositoryPort(Protocol):
    def get_concept_pairs(self, material_id: int) -> List[Tuple[str, str]]: ...
    def get_concept_pairs_for_student(self, student_id: int) -> List[Tuple[str, str]]: ...


class DocumentServicePort(Protocol):
    def extract_text(self, file_content: bytes, file_type: str) -> str: ...


class MaterialUpserterPort(Protocol):
    def upsert(self, student_id: int, text: str, source_name: str, topics: Dict[str, List[str]] | None) -> Any: ...


class MaterialDeletionPolicyPort(Protocol):
    def delete(self, user_id: int, material_id: int) -> bool: ...


class TopicAIServicePort(Protocol):
    client: Any | None
    def extract_topics(self, text: str) -> Dict[str, List[str]]: ...


class TopicServicePort(Protocol):
    def extract_topics(self, text: str, ai_service: "TopicAIServicePort") -> Dict[str, List[str]]: ...


class MaterialServicePort(Protocol):
    async def upload_material(
        self,
        user_id: int,
        file_content: bytes,
        filename: str,
        file_type: str | None,
        ai_service: "TopicAIServicePort"
    ) -> Dict: ...
    def analyze_topics(self, user_id: int, ai_service: "TopicAIServicePort") -> Dict: ...
    def get_current_material(self, user_id: int) -> Dict | None: ...
    def clear_material(self, user_id: int) -> bool: ...
    def list_materials(self, user_id: int) -> List[Dict]: ...
    def activate_material(self, user_id: int, material_id: int) -> bool: ...
    def delete_material(self, user_id: int, material_id: int) -> bool: ...


class TopicSelectorPort(Protocol):
    def select(
        self,
        user_id: int,
        material_id: int | None,
        requested_topics: List[str] | None
    ) -> Tuple[List[str], List[str]]: ...
